# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Research"
  url = "#publications"
  weight = 25

# [[main]]
#  name = "Other Projects"
#  url = "#projects"
#  weight = 35


# [[main]]
#  name = "Teaching"
#  url = "#courses"
#  weight = 40

[[main]]
  name = "Bio"
  url = "extended-bio/"
  weight = 50

[[main]]
  name = "Student research FAQ"
  url = "files/StudentResearch.pdf"
  weight = 50

[[main]]
  name = "Graduate advising"
  url = "files/OConnell_GradAdvising.pdf"
  weight = 52
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/OConnell_CV.pdf"
    weight = 45
